language: generic

script:
  - test $(grep '<div class="item">' index.html | wc -l) -le 6
  - test $(grep '<div class="item">' index.html | wc -l) -ge 5

deploy:
  provider: pages
  github-token: $GITHUB_TOKEN
  on:
    branch: master
